# -*- coding: utf-8 -*-
"""Microsoft-phi-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhIrFqkE_-IcnUjESKJd8xVpC2e2myrE
"""

!pip install -q accelerate -U
!pip install -q bitsandbytes -U
!pip install -q trl -U
!pip install -q peft -U
!pip install -q transformers -U
!pip install -q datasets -U
!pip install bitsandbytes --prefer-binary --upgrade

import pandas as pd
from datasets import load_dataset, Dataset, DatasetDict

df = pd.read_csv("/content/Follow_Up_Dataset.csv")
df = df.dropna()

df.head()

df["question"].value_counts()

df['text'] = "\nAnswer: " + df['answer'] + "\n\nFollow Up Question: " + df['follow-up questions']

print(df['text'][0])

df = df[['question', 'text']]

df.head()

dataset = Dataset.from_pandas(df)
dataset = dataset.shuffle(seed=0)
dataset = dataset.train_test_split(test_size=0.1)

dataset['test'][0]

dummy = df.copy()
dummy['question_tokens'] = dummy['question'].apply(lambda x: len(x.split())*1.5)
dummy['text_tokens'] = dummy['text'].apply(lambda x: len(x.split())*1.5)

dummy['question_tokens'].hist()

dummy['text_tokens'].hist()

del dummy

def formatting_func(example):
    text = f"""
Given the Question of a topic, you need to generate answer and follow up questions of this topic.
### Question: {example['question']}
### Result: {example['text']}
"""
    return text

print(formatting_func(dataset['test'][0]))

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

base_model_id = "microsoft/phi-2"

model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    trust_remote_code=True,
    torch_dtype=torch.float16,
    load_in_8bit=True,
    device_map='auto',
)

tokenizer = AutoTokenizer.from_pretrained(
    base_model_id,
    padding_size='left',
    add_eos_token=True,
    add_bos_token=True,
    use_fast=False
)

tokenizer.pad_token = tokenizer.eos_token

max_length = 100

def tokenize(prompt):
    result = tokenizer(
        formatting_func(prompt),
        truncation=True,
        max_length=max_length,
        padding="max_length"
    )

    result['labels'] = result['input_ids'].copy()

    return result

dataset = dataset.map(tokenize)

from peft import LoraConfig, get_peft_model

target_modules = ["Wqvk", "fc1", "fc2"]

config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules=target_modules,
    bias = 'none',
    lora_dropout=0.05,
    task_type = 'CAUSAL_LM'
)

model = get_peft_model(model, config)

def print_trainable_parameters(model):
    trainable_params = 0
    all_params = 0
    for _, param in model.named_parameters():
        all_params += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(
        f'trainable params: {trainable_params} || all params: {all_params} || trainable%: {100 * (trainable_params / all_params)}'
    )

print_trainable_parameters(model)

from transformers import TrainingArguments, Trainer, DataCollatorForLanguageModeling
from datetime import datetime

# project = 'train_dir'
ckpt_steps = 75
run_name = 'phi-2_finetune_on_follow_up_dataset'
output_dir = './' + run_name

args = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=1,
    max_steps=1500,
    learning_rate=2.5e-5, # Want a small lr for finetuning
    optim="paged_adamw_8bit",
    logging_steps=ckpt_steps,              # When to start reporting loss
    logging_dir="./logs",        # Directory for storing logs
    save_strategy="steps",       # Save the model checkpoint every logging step
    save_steps=ckpt_steps,                # Save checkpoints every 50 steps
    eval_strategy="steps", # Evaluate the model every logging step
    eval_steps=ckpt_steps,               # Evaluate and save checkpoints every 50 steps
    do_eval=True,                # Perform evaluation at the end of training
)

trainer = Trainer(
    model = model,
    args = args,
    train_dataset= dataset['train'],
    eval_dataset= dataset['test'],
    data_collator= DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

model.config.use_cache = False

trainer.train()

import torch
base_model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    trust_remote_code=True,
    load_in_8bit=True,
    torch_dtype=torch.float16
)

eval_tokenizer = AutoTokenizer.from_pretrained(
    base_model_id,
    add_bos_token=True,
    trust_remote_code=True,
    use_fast=False
)
eval_tokenizer.pad_token = eval_tokenizer.eos_token

from peft import PeftModel

ft_model = PeftModel.from_pretrained(base_model, './phi-2_finetune_on_follow_up_dataset/checkpoint-1500/')

def generate(eval_prompt):
    model_input = eval_tokenizer(eval_prompt, return_tensors="pt").to("cuda")

    ft_model.eval()
    with torch.no_grad():
        output = ft_model.generate(**model_input, max_new_tokens=200, repetition_penalty=1.20)
        result = eval_tokenizer.decode(output[0], skip_special_tokens=True)

        return result

import re

def clean_output(raw_output):
    # Step 1: Extract the answer text
    answer_match = re.search(r"Answer:\s*(.*?)(Follow[\s\-]?up Questions?:|$)", raw_output, re.DOTALL | re.IGNORECASE)
    answer = answer_match.group(1).strip() if answer_match else "[Answer missing]"

    # Step 2: Extract follow-up block
    followup_match = re.search(r"Follow[\s\-]?up Questions?:\s*(.*)", raw_output, re.DOTALL | re.IGNORECASE)
    followup_raw = followup_match.group(1).strip() if followup_match else ""

    # Step 3: Normalize — remove double `1. 1.` etc.
    followup_raw = re.sub(r'\b1\.\s*1\.\s*', '1. ', followup_raw)

    # Step 4: Split on numbered patterns OR semicolons
    followup_lines = re.split(r'(?:\n?\d+\.\s+|\s*;\s*)', followup_raw)

    # Step 5: Clean each line
    followup_cleaned = [q.strip() for q in followup_lines if q.strip() and len(q.split()) > 2]

    # Step 6: Limit to top 5
    followup_top5 = followup_cleaned[:5]

    # Step 7: Renumber
    followup_final = "\n".join([f"{i+1}. {q}" for i, q in enumerate(followup_top5)])

    return f"Answer: {answer}\n\nFollow-up Questions:\n{followup_final}"

def wrap_prompt(question):
    return f"""
Given the Question of a topic, you need to generate answer and follow up questions of this topic.
### Question: {question}
### Result:
"""

eval_prompt = wrap_prompt("What is the capital of India?")

print(clean_output(generate(eval_prompt)))

from huggingface_hub import login
login()

model.save_pretrained("Microsoft-phi-2-follow-up-question")
tokenizer.save_pretrained("Microsoft-phi-2-follow-up-question")

model.push_to_hub("niloydas19/Microsoft-phi-2-follow-up-question")
tokenizer.push_to_hub("niloydas19/Microsoft-phi-2-follow-up-question")

!zip -r Microsoft-phi-2-follow-up-question.zip Microsoft-phi-2-follow-up-question

from google.colab import files
files.download("Microsoft-phi-2-follow-up-question.zip")